### ISSUE TITLE
Asset Repository

### ISSUE THREAD

**Issue by bafu** [numbersprotocol/mediant#1]
This is a hack to host images, not a real issue.

---
![ic_launcher_foreground_xxhdpi](https://user-images.githubusercontent.com/292790/66003547-5398cf80-e49e-11e9-9ad5-1e372c7d2e54.png)

**Comment by seanwu1105** [comment]
![Screenshot_1571810672](https://user-images.githubusercontent.com/14951000/67362997-ff65a480-f59e-11e9-8963-aa9adc6184f2.png)
![Screenshot_1571810640](https://user-images.githubusercontent.com/14951000/67363000-fffe3b00-f59e-11e9-90dc-1e8f86b42ca6.png)
![Screenshot_1571810628](https://user-images.githubusercontent.com/14951000/67363002-fffe3b00-f59e-11e9-9565-abb7789fe8aa.png)
![Screenshot_1571810622](https://user-images.githubusercontent.com/14951000/67363004-fffe3b00-f59e-11e9-9e7d-738339dd6d03.png)
![Screenshot_1571810574](https://user-images.githubusercontent.com/14951000/67363006-0096d180-f59f-11e9-9d5f-fbbb898dab2f.png)

**Comment by seanwu1105** [comment]
![Screenshot_1574600840](https://user-images.githubusercontent.com/14951000/69495169-f863e600-0efe-11ea-9d8d-fcc55adc6f69.png)
![Screenshot_1574600943](https://user-images.githubusercontent.com/14951000/69495170-f863e600-0efe-11ea-867c-bbbb3166d7bb.png)
![Screenshot_1574601004](https://user-images.githubusercontent.com/14951000/69495171-f863e600-0efe-11ea-9580-3753aca0f741.png)
![Screenshot_1574601010](https://user-images.githubusercontent.com/14951000/69495173-f8fc7c80-0efe-11ea-8597-9026f5f232c1.png)
![Screenshot_1574601018](https://user-images.githubusercontent.com/14951000/69495174-f8fc7c80-0efe-11ea-897a-f1b027c41a8f.png)
![Screenshot_1574601023](https://user-images.githubusercontent.com/14951000/69495175-f8fc7c80-0efe-11ea-9285-2b4394da72b5.png)

**Comment by seanwu1105** [comment]
![Webp net-resizeimage](https://user-images.githubusercontent.com/14951000/70017197-78ecab80-15bd-11ea-89ea-7e70c5098568.png)
